test_app/config/routes.rb
BipApp::Application.routes.draw do
  resources :users do
    member do
      put :test_respond_with
      get :double_init
      get :show_ajax
      get :email_field
    end
  end

  namespace :cuca do
    resources :cars
  end

  namespace :admin do
    resources :users
  end

  root :to => "users#index"
end

test_app/app/models/cuca/car.rb
module Cuca
  class Car < ActiveRecord::Base

  end
end

test_app/app/models/user.rb
class User < ActiveRecord::Base
  validates :name,
    :length => { :minimum => 2, :maximum => 24, :message => "has invalid length"},
    :presence => {:message => "can't be blank"}
  validates :last_name,
    :length => { :minimum => 2, :maximum => 50, :message => "has invalid length"},
    :presence => {:message => "can't be blank"}
  validates :address,
    :length => { :minimum => 5, :message => "too short length"},
    :presence => {:message => "can't be blank"}
  validates :email,
    :presence => {:message => "can't be blank"},
    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "has wrong email format"}
  validates :zip, :numericality => true, :length => { :minimum => 5 }
  validates_numericality_of :money, :allow_blank => true
  validates_numericality_of :money_proc, :allow_blank => true

  alias_attribute :money_custom, :money

  def address_format
    "<b>addr => [#{address}]</b>".html_safe
  end

  def markdown_desc
    RDiscount.new(description).to_html.html_safe
  end
end

test_app/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      @user.update_attributes(params[:user])
      format.json { respond_with_bip(@user) }
    end
  end
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

test_app/app/controllers/cuca/cars_controller.rb
module Cuca
  class CarsController < ApplicationController
    def show
      @car = Car.find params[:id]
    end

    def update
      @car = Car.find params[:id]

      respond_to do |format|
        @car.update_attributes params[:cuca_car]
        format.json { respond_with_bip(@car) }
      end
    end
  end
end

test_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @countries = COUNTRIES.to_a

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def email_field
    @user = User.find(params[:id])
    render :action => :email_field, :layout => false
  end

  def show_ajax
    @user = User.find(params[:id])
    @countries = COUNTRIES.to_a
  end

  def double_init
    @user = User.find(params[:id])
    @countries = COUNTRIES.to_a
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.json { respond_with_bip(@user) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@user) }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/users_helper.rb
#encoding: utf-8
module UsersHelper
  def height_collection
    [
      %{5' 1"} ,
      %{5' 2"} ,
      %{5' 3"} ,
      %{5' 4"} ,
      %{5' 5"} ,
      %{5' 6"} ,
      %{5' 7"} ,
      %{5' 8"} ,
      %{5' 9"} ,
      %{5' 10"},
      %{5' 11"},
      %{6' 0"} ,
      %{6' 1"} ,
      %{6' 2"} ,
      %{6' 3"} ,
      %{6' 4"} ,
      %{6' 5"} ,
      %{6' 6"}
    ]
  end

  def bb(value)
    "#{value} €"
  end
end

test_app/app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<div id="user_account">
  <h1>User details</h1>
  <%= link_to "Go back to USERS", users_path %>
  <p style="margin-left:48em">Click to edit</p>
  <table>
    <tr>
      <td id="name">
        <%= best_in_place [:admin, @user], :name %>
      </td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td id="last_name">
        <%= best_in_place [:admin, @user], :last_name, :nil => "Nothing to show" %>
      </td>
    </tr>
  </table>
</div>

test_app/app/views/cuca/cars/show.html.erb
<p id="notice"><%= notice %></p>
<div id="user_account">
  <h1>Car details</h1>
  <p style="margin-left:48em">Click to edit</p>
  <table>
    <tr>
      <td>Model</td>
      <td id="model">
        <%= best_in_place @car, :model %>
      </td>
    </tr>
  </table>
</div>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Best In Place TEST APP</title>
  <%= stylesheet_link_tag "scaffold", "style", "jquery-ui-1.8.16.custom" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

test_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.select :height, height_collection %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= 
      f.select :country, COUNTRIES.map {|c|
        v0 = c[0]
        c[0] = c[1]
        c[1] = v0
        c
      }
    %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

test_app/app/views/users/double_init.html.erb
<p>This is a page that initializes best in place two times with testing purposes</p>
<div id="user_account">
  <h1>User details</h1>
  <%= link_to "Go back to USERS", users_path %>
  <p style="margin-left:48em">Click to edit</p>
  <table>
    <tr>
      <td>Name <a id="editme" href="#">(edit me)</a></td>
      <td id="name">
        <%= best_in_place @user, :name, :type => :input, :activator => "#editme" %>
      </td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td id="last_name">
        <%= best_in_place @user, :last_name, :nil => "Nothing to show", :path => test_respond_with_user_path(@user) %>
      </td>
    </tr>
    <tr>
      <td>Email</td>
      <td id="email">
        <%= best_in_place @user, :email %>
      </td>
    </tr>
    <tr>
      <td>Address</td>
      <td id="address">
        <%= best_in_place @user, :address %>
      </td>
    </tr>
    <tr>
      <td>ZIP</td>
      <td id="zip">
        <%= best_in_place @user, :zip %>
      </td>
    </tr>
    <tr>
      <td>Country</td>
      <td id="country">
        <%= best_in_place @user, :country, :type => :select, :collection => @countries %>
      </td>
    </tr>
    <tr>
      <td>Receive newsletter?</td>
      <td id="receive_email">
        <%= best_in_place @user, :receive_email, :type => :checkbox, :collection => ["No thanks", "Yes of course"] %>
      </td>
    </tr>
    <tr>
      <td>User description</td>
      <td id="description">
        <%= best_in_place @user, :description, :type => :textarea, :sanitize => false %>
      </td>
    </tr>
    <tr>
      <td>Alternative Money</td>
      <td id="alt_money">
        <%= best_in_place @user, :money, :display_with => :number_to_currency, :helper_options => {:unit => "€"} %>
      </td>
    </tr>
  </table>
  <br />
  <hr />

</div>

<%= javascript_tag do %>
  $(document).ready(function() {
    /* Activating Best In Place */
    jQuery(".best_in_place").best_in_place();
  });
<% end %>

test_app/app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

test_app/app/views/users/email_field.html.erb
<%= best_in_place @user, :email %>

test_app/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th colspan="2">Name</th>
    <th>Last name</th>
    <th>Country</th>
  </tr>

<% @users.each do |user| %>
  <tr id="user_<%= user.id %>">
    <td class="name">
      <%= best_in_place user, :name,
                        activator: "#edit_#{user.id}",
                        display_with: :link_to, 
                        helper_options: user_path(user) %>
    </td>
    <td><small><a href="#" id="edit_<%= user.id %>">edit</a></small></td>
    <td><%= user.last_name %></td>
    <td><%= COUNTRIES[user.country.to_i] %></td>
  </tr>
<% end %>
</table>

<br />

test_app/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

test_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div id="user_account">
  <h1>User details</h1>
  <%= link_to "Go back to USERS", users_path %>
  <p style="margin-left:48em">Click to edit</p>
  <table>
    <tr>
      <td>Name <a id="editme" href="#">(edit me)</a></td>
      <td id="name">
        <%= best_in_place @user, :name, :type => :input, :activator => "#editme" %>
      </td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td id="last_name">
        <%= best_in_place @user, :last_name, :nil => "Nothing to show" %>
      </td>
    </tr>
    <tr>
      <td>Height</td>
      <td id="height">
        <%= best_in_place @user, :height, :type => :select, :collection => height_collection.zip(height_collection), :sanitize => false %>
      </td>
    </tr>
    <tr>
      <td>Email</td>
      <td id="email">
        <%= best_in_place @user, :email %>
      </td>
    </tr>
    <tr>
      <td>Birth date</td>
      <td id="birth_date">
        <%= best_in_place @user, :birth_date, :type => :date %>
      </td>
    </tr>
    <tr>
      <td>Address</td>
      <td id="address">
        <%= best_in_place @user, :address, :display_as => :address_format %>
      </td>
    </tr>
    <tr>
      <td>ZIP</td>
      <td id="zip">
        <%= best_in_place @user, :zip %>
      </td>
    </tr>
    <tr>
      <td>Country</td>
      <td id="country">
        <%= best_in_place @user, :country, :type => :select, :collection => @countries, :inner_class => :some_class %>
      </td>
    </tr>
    <tr>
      <td>Receive newsletter?</td>
      <td id="receive_email">
        <%= best_in_place @user, :receive_email, :type => :checkbox, :collection => ["No thanks", "Yes of course"] %>
      </td>
    </tr>
    <tr>
      <td>Receive newsletter (image)?</td>
      <td id="receive_email_image">
        <%= best_in_place @user, :receive_email, :type => :checkbox, :collection => [image_tag('no.png'), image_tag('yes.png')] %>
      </td>
    </tr>
    <tr>
      <td>Favorite color</td>
      <td id="favorite_color">
        <%- opts = { :ok_button => 'Do it!', :cancel_button => 'Nope', :ok_button_class => 'custom-submit other-custom-submit', :cancel_button_class => 'custom-cancel other-custom-cancel' } %>
        <%- opts.delete(:ok_button) if params[:suppress_ok_button] %>
        <%- opts[:nil] = "<span class='nil'>Click to add your favorite color</span>" %>
        <%= best_in_place @user, :favorite_color, opts %>
      </td>
    </tr>
    <tr>
      <td>Favorite locale</td>
      <td id="favorite_locale">
        <%= best_in_place @user, :favorite_locale, :nil => "N/A" %>
      </td>
    </tr>
    <tr>
      <td>Favorite books</td>
      <td id="favorite_books">
        <%- opts = { :type => :textarea, :ok_button => 'Save', :cancel_button => 'Cancel' } %>
        <%- opts.delete(:ok_button) if params[:suppress_ok_button] %>
        <%= best_in_place @user, :favorite_books, opts %>
      </td>
    </tr>
    <tr>
      <td>User description</td>
      <td id="description">
        <%= best_in_place @user, :description, :display_as => :markdown_desc, :type => :textarea, :sanitize => false %>
      </td>
    </tr>
    <tr>
      <td>Simple-formatted user description</td>
      <td id="dw_description">
        <%= best_in_place @user, :description, :display_with => :simple_format, :type => :textarea %>
      </td>
    </tr>
    <tr>
      <td>Money</td>
      <td id="money">
        <%= best_in_place @user, :money, :display_with => :number_to_currency %>
      </td>
    </tr>
    <tr>
      <td>Money with proc</td>
      <td id="money_proc">
        <%= best_in_place @user, :money_proc, :display_with => lambda{ |v| v.blank? ? "No money" : number_to_currency(v) } %>
      </td>
    </tr>
    <tr>
      <td>Money with custom helper</td>
      <td id="money_custom">
        <%= best_in_place @user, :money_custom, :display_with => lambda { |x| bb(x) } %>
      </td>
    </tr>
    <tr>
      <td>Favorite Movie</td>
      <td id="favorite_movie">
        <%- opts = { :ok_button => 'Do it!', :cancel_button => 'Nope', :use_confirm => false } %>
        <%- opts.delete(:ok_button) if params[:suppress_ok_button] %>
        <%= best_in_place @user, :favorite_movie, opts %>
      </td>
    </tr>
  </table>
  <br />
  <hr />
  <p>Try the <b>features of Best In Place</b>:</p>
  <ul>
  <li>Try giving wrong email values or too short address, inputs to see server errors.</li>
  <li>Click on newsletter to change a boolean value</li>
  <li>Click on country to change the value in a collection of values</li>
  <li>Use the external handler to change the value of the name</li>
  <li>Try making changes inside inputs or textareas and then press the ESC key to recover the old value</li>
  </ul>
  <p>More information on <a href="http://github.com/bernat/best_in_place">github</a> or <a href="http://blog.bernatfarrero.com/in-place-editing-with-javascript-jquery-and-rails-3/">bernatfarrero.com</a>.</p>

</div>

test_app/app/views/users/show_ajax.html.erb
<%= render :template => 'users/show' %>
<script>
  $(document).ready(function () {
    $('#email').html('');
    setTimeout( function () { //give time to the other document.ready callbacks to be executed
      $.get("/users/<%= params[:id]%>/email_field", function(data, status) {
        $('#email').html(data);
      });
    },
    500);
  });
</script>